[package]
name = "plumb-patch"
version.workspace = true
edition.workspace = true

[dependencies]
plumb-core = { path = "../plumb-core" }
plumb-psg = { path = "../plumb-psg" }
serde = { workspace = true }
serde_json = { workspace = true }
petgraph = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[features]
default = []
