[package]
name = "plumb-compiler"
version.workspace = true
edition.workspace = true

[dependencies]
plumb-core = { path = "../plumb-core" }
plumb-artifacts = { path = "../plumb-artifacts" }
plumb-psg = { path = "../plumb-psg" }
plumb-patch = { path = "../plumb-patch" }
plumb-validation = { path = "../plumb-validation" }
plumb-inference = { path = "../plumb-inference" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[features]
default = []
